# Generated by Django 3.2.7 on 2021-09-05 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazaar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderStaging',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='SalesOrder',
        ),
    ]
