# Generated by Django 3.2.7 on 2021-09-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
